### ISSUE TITLE
Problém v souvislosti s  InputStream Adaptiv verze 21.4.10

### ISSUE THREAD

**Issue by little-george-cz** [waladir/plugin.video.o2tv#2]
V diskuzi na www.xbmc-kodi.cz v tématu o tomto doplňku je zmínka o pádech KODI na Windows 10 v souvislosti s InputStream Adaptiv verze 21.4.10. Stačí zaktualizovat knihovnu Microsoft Visual C++ 2015-2022 na poslední verzi 14.40.33810 a je po problému.

**Comment by waladir** [comment]
Díky za info. Dopsal jsem to do vlákna na fóru.
